# Generated by Django 2.0.2 on 2018-03-24 04:41

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Comment',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Letter_pdf_Comment', models.CharField(max_length=150)),
            ],
        ),
        migrations.CreateModel(
            name='Letter_pdf',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('addressing_officer', models.CharField(max_length=100)),
                ('project', models.CharField(max_length=100)),
                ('modified_date', models.DateField(auto_now_add=True)),
                ('created_date', models.DateField(auto_now_add=True)),
                ('creator', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='letterpdfs', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.AddField(
            model_name='comment',
            name='Comment_Letter_pdf',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Letter_pdf.Letter_pdf'),
        ),
        migrations.AddField(
            model_name='comment',
            name='Letter_pdf_Comment_Author',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='commentletterpdf', to=settings.AUTH_USER_MODEL),
        ),
    ]
