# Generated by Django 2.0.2 on 2018-03-31 11:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Letter_pdf', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='letter_pdf',
            old_name='addressing_officer',
            new_name='Letter_pdf_Addressing_Officer',
        ),
        migrations.RenameField(
            model_name='letter_pdf',
            old_name='created_date',
            new_name='Letter_pdf_Created_Date',
        ),
        migrations.RenameField(
            model_name='letter_pdf',
            old_name='creator',
            new_name='Letter_pdf_Creator',
        ),
        migrations.RenameField(
            model_name='letter_pdf',
            old_name='modified_date',
            new_name='Letter_pdf_Modified_Date',
        ),
        migrations.RenameField(
            model_name='letter_pdf',
            old_name='project',
            new_name='Letter_pdf_Project',
        ),
    ]
