# Generated by Django 2.0.2 on 2018-03-24 05:31

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Comment',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Location_Comment', models.CharField(max_length=150)),
            ],
        ),
        migrations.CreateModel(
            name='Location',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Area', models.CharField(max_length=100)),
                ('Budget', models.CharField(max_length=100)),
                ('City', models.CharField(max_length=100)),
                ('Description', models.CharField(max_length=100)),
                ('District', models.CharField(max_length=100)),
                ('Locality', models.CharField(max_length=100)),
                ('Location_name', models.CharField(max_length=100)),
                ('Location_postal_address', models.CharField(max_length=100)),
                ('Location_financial', models.CharField(max_length=100)),
                ('Location_id', models.CharField(max_length=100)),
                ('Location_latitude', models.CharField(max_length=100)),
                ('Location_longitude', models.CharField(max_length=100)),
                ('Location_subcategory', models.CharField(max_length=100)),
                ('Modifications_allowed', models.CharField(max_length=100)),
                ('Ownership_status', models.CharField(max_length=100)),
                ('Pincode', models.CharField(max_length=100)),
                ('Restrictions', models.CharField(max_length=100)),
                ('State', models.CharField(max_length=100)),
                ('Street_address', models.CharField(max_length=100)),
                ('Surrounding', models.CharField(max_length=100)),
                ('modified_date', models.DateField(auto_now_add=True)),
                ('created_date', models.DateField(auto_now_add=True)),
                ('Authorities_involved', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='locationss', to=settings.AUTH_USER_MODEL)),
                ('Location_creator', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='crlocations', to=settings.AUTH_USER_MODEL)),
                ('creator', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='userlocations', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.AddField(
            model_name='comment',
            name='Comment_Location',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Location.Location'),
        ),
        migrations.AddField(
            model_name='comment',
            name='Location_Comment_Author',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='commentlocation', to=settings.AUTH_USER_MODEL),
        ),
    ]
