# Generated by Django 2.0.2 on 2018-04-02 06:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Location', '0003_auto_20180401_2156'),
    ]

    operations = [
        migrations.RenameField(
            model_name='location',
            old_name='Location_financial',
            new_name='Location_Financial',
        ),
    ]
