# Generated by Django 2.0.2 on 2018-04-02 11:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Location_Category', '0002_auto_20180402_0420'),
    ]

    operations = [
        migrations.AlterField(
            model_name='location_category',
            name='Location_Category_No',
            field=models.IntegerField(max_length=100),
        ),
    ]
