# Generated by Django 2.0.2 on 2018-03-24 06:53

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Comment',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Location_Comment', models.CharField(max_length=150)),
            ],
        ),
        migrations.CreateModel(
            name='Location_Amenitie',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Carparking', models.BooleanField()),
                ('Carparking_latitide', models.CharField(max_length=100)),
                ('Carparking_longitude', models.CharField(max_length=100)),
                ('Catering_base', models.BooleanField()),
                ('Catering_base_latitude', models.CharField(max_length=100)),
                ('Catering_base_longitude', models.CharField(max_length=100)),
                ('Controlling_status', models.CharField(max_length=100)),
                ('Genset_parking', models.BooleanField()),
                ('Genset_parking_latitude', models.IntegerField()),
                ('Genset_parking_longitude', models.IntegerField()),
                ('Locationid', models.IntegerField()),
                ('Truck_parking_latitude', models.IntegerField()),
                ('Truck_parking_longitude', models.IntegerField()),
                ('Vanity_parking', models.BooleanField()),
                ('Vanity_parking_latitude', models.IntegerField()),
                ('Vanity_parking_longitude', models.IntegerField()),
                ('Washroom', models.BooleanField()),
                ('modified_date', models.DateField()),
                ('created_date', models.DateField()),
                ('creator', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='locatonamenities', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.AddField(
            model_name='comment',
            name='Comment_Location',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Location_Amenitie.Location_Amenitie'),
        ),
        migrations.AddField(
            model_name='comment',
            name='Location_Comment_Author',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='commentLocation_Amenitie', to=settings.AUTH_USER_MODEL),
        ),
    ]
