# Generated by Django 2.0.2 on 2018-03-24 07:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Location_Amenitie', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='location_amenitie',
            name='Carparking_latitide',
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name='location_amenitie',
            name='Carparking_longitude',
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name='location_amenitie',
            name='Catering_base_latitude',
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name='location_amenitie',
            name='Catering_base_longitude',
            field=models.IntegerField(),
        ),
    ]
